export const entityTexts = {
  en: {
    babysitter: "Babysitter",
    parent: "Parent",
    email: "Email",
    password: "Password",
    age: "Age",
    location: "Location",
    preferences: "Preferences",
    experience: "Experience",
    about: "About",
    price: "Hourly rate",
    likes: "Likes",
    address: "Address",
    phone: "Phone",
    name: "Name",
    amount: "Number of children",
    city: "City",
    street: "Street",
    buildingNumber: "Building number",
    image: "Image",
    noUsers: "No Users",
    close: "Close",
    back: "Back",
    submit: "Submit",
  },
  he: {
    babysitter: "בייביסיטר",
    parent: "הורה",
    email: "אימייל",
    password: "סיסמה",
    age: "גיל",
    location: "מיקום",
    preferences: "העדפות",
    experience: "ניסיון",
    about: "עליי",
    price: "תעריף לשעה",
    likes: "לייקים",
    address: "כתובת",
    phone: "טלפון",
    name: "שם",
    amount: "מספר ילדים",
    city: "עיר",
    street: "רחוב",
    buildingNumber: "מספר בניין",
    image: "תמונה",
    noUsers: "אין משתמשים",
    close: "סגירה",
    back: "חזרה",
    submit: "שליחה",
  },
} as const;
