export const feedbackTexts = {
  en: {
    feedbackCommentErrorMessage: "Please add a rating and write a short comment.",
    feedbackCommentErrorTitle: "Comment was not sent",
    feedbackCommentSuccessMessage: "Your review is now visible on this profile.",
    feedbackCommentSuccessTitle: "Comment sent",
    feedbackGenericErrorMessage: "Something went wrong. Please try again.",
    feedbackLoginErrorTitle: "Login failed",
    feedbackLoginSuccessMessage: "You are now connected to your workspace.",
    feedbackLoginSuccessTitle: "Welcome back",
    feedbackLogoutErrorTitle: "Logout failed",
    feedbackLogoutSuccessMessage: "You were signed out successfully.",
    feedbackLogoutSuccessTitle: "Logged out",
    feedbackOrderRequestErrorTitle: "Order request was not sent",
    feedbackOrderRequestSuccessMessage: "The babysitter will see your request soon.",
    feedbackOrderRequestSuccessTitle: "Order request sent",
    feedbackOrderStatusErrorTitle: "Status was not updated",
    feedbackOrderStatusSuccessMessage: "The order status was saved.",
    feedbackOrderStatusSuccessTitle: "Status updated",
    feedbackPasswordMismatchMessage: "The password confirmation must match the new password.",
    feedbackPasswordResetConfirmSuccessMessage: "You can now log in with the new password.",
    feedbackPasswordResetConfirmSuccessTitle: "Password updated",
    feedbackPasswordResetErrorTitle: "Password reset failed",
    feedbackPasswordResetRequestSuccessMessage: "If the email exists, a reset link was sent.",
    feedbackPasswordResetRequestSuccessTitle: "Reset link sent",
    feedbackPasswordTooShortMessage: "Password must be at least 8 characters.",
    feedbackProfileUpdateErrorTitle: "Profile was not updated",
    feedbackProfileUpdateSuccessMessage: "Your profile changes were saved.",
    feedbackProfileUpdateSuccessTitle: "Profile updated",
    feedbackRegisterBabysitterSuccessMessage: "Your babysitter account was created successfully.",
    feedbackRegisterErrorTitle: "Registration failed",
    feedbackRegisterParentSuccessMessage: "Your parent account was created successfully.",
    feedbackRegisterSuccessTitle: "Registration complete",
  },
  he: {
    feedbackCommentErrorMessage: "צריך לבחור דירוג ולכתוב תגובה קצרה.",
    feedbackCommentErrorTitle: "התגובה לא נשלחה",
    feedbackCommentSuccessMessage: "הביקורת שלך מוצגת עכשיו בפרופיל.",
    feedbackCommentSuccessTitle: "התגובה נשלחה",
    feedbackGenericErrorMessage: "משהו השתבש. נסו שוב בעוד רגע.",
    feedbackLoginErrorTitle: "ההתחברות נכשלה",
    feedbackLoginSuccessMessage: "התחברת למערכת בהצלחה.",
    feedbackLoginSuccessTitle: "ברוך שובך",
    feedbackLogoutErrorTitle: "ההתנתקות נכשלה",
    feedbackLogoutSuccessMessage: "התנתקת מהמערכת בהצלחה.",
    feedbackLogoutSuccessTitle: "התנתקת",
    feedbackOrderRequestErrorTitle: "בקשת ההזמנה לא נשלחה",
    feedbackOrderRequestSuccessMessage: "הבייביסיטר תראה את הבקשה בקרוב.",
    feedbackOrderRequestSuccessTitle: "בקשת ההזמנה נשלחה",
    feedbackOrderStatusErrorTitle: "הסטטוס לא עודכן",
    feedbackOrderStatusSuccessMessage: "סטטוס ההזמנה נשמר.",
    feedbackOrderStatusSuccessTitle: "הסטטוס עודכן",
    feedbackPasswordMismatchMessage: "אימות הסיסמה חייב להיות זהה לסיסמה החדשה.",
    feedbackPasswordResetConfirmSuccessMessage: "אפשר להתחבר עכשיו עם הסיסמה החדשה.",
    feedbackPasswordResetConfirmSuccessTitle: "הסיסמה עודכנה",
    feedbackPasswordResetErrorTitle: "איפוס הסיסמה נכשל",
    feedbackPasswordResetRequestSuccessMessage: "אם האימייל קיים, נשלח אליו קישור איפוס.",
    feedbackPasswordResetRequestSuccessTitle: "קישור האיפוס נשלח",
    feedbackPasswordTooShortMessage: "הסיסמה חייבת לכלול לפחות 8 תווים.",
    feedbackProfileUpdateErrorTitle: "הפרופיל לא עודכן",
    feedbackProfileUpdateSuccessMessage: "השינויים בפרופיל נשמרו.",
    feedbackProfileUpdateSuccessTitle: "הפרופיל עודכן",
    feedbackRegisterBabysitterSuccessMessage: "חשבון הבייביסיטר נוצר בהצלחה.",
    feedbackRegisterErrorTitle: "ההרשמה נכשלה",
    feedbackRegisterParentSuccessMessage: "חשבון ההורה נוצר בהצלחה.",
    feedbackRegisterSuccessTitle: "ההרשמה הושלמה",
  },
} as const;
