export const formTexts = {
  en: {
    emailPlaceholder: "Please enter an email",
    passwordPlaceholder: "Please enter a password",
    registerTitle: "Register",
    registerSubtitle: "Welcome to the Registration page",
    fullNamePlaceholder: "Enter your full name",
    namePlaceholder: "Enter your name",
    amountPlaceholder: "Enter the number of children",
    cityPlaceholder: "Enter your city",
    streetPlaceholder: "Enter your street",
    buildingNumberPlaceholder: "Enter your building number",
    phonePlaceholder: "Enter your phone number",
    imagePlaceholder: "Enter your image URL",
    addressPlaceholder: "Enter your address",
    agePlaceholder: "Enter your age",
    experiencePlaceholder: "Enter your experience",
    aboutPlaceholder: "Tell us about yourself",
    pricePlaceholder: "Enter your hourly rate",
    registerParentSubmit: "Create parent account",
    registerBabysitterSubmit: "Create babysitter account",
    preferenceInfancy: "Infancy",
    preferenceSpecialEducation: "Special education",
    preferenceAgeFive: "Age 5 and up",
    preferenceRewards: "Rewards",
    preferenceWithoutFood: "Without food",
    preferenceNoHomework: "No homework",
  },
  he: {
    emailPlaceholder: "הכניסו אימייל",
    passwordPlaceholder: "הכניסו סיסמה",
    registerTitle: "הרשמה",
    registerSubtitle: "ברוכים הבאים למסך ההרשמה",
    fullNamePlaceholder: "הכניסו שם מלא",
    namePlaceholder: "הכניסו שם",
    amountPlaceholder: "הכניסו מספר ילדים",
    cityPlaceholder: "הכניסו עיר",
    streetPlaceholder: "הכניסו רחוב",
    buildingNumberPlaceholder: "הכניסו מספר בניין",
    phonePlaceholder: "הכניסו מספר טלפון",
    imagePlaceholder: "הכניסו כתובת תמונה",
    addressPlaceholder: "הכניסו כתובת",
    agePlaceholder: "הכניסו גיל",
    experiencePlaceholder: "הכניסו ניסיון",
    aboutPlaceholder: "ספרו על עצמכם",
    pricePlaceholder: "הכניסו תעריף לשעה",
    registerParentSubmit: "יצירת חשבון הורה",
    registerBabysitterSubmit: "יצירת חשבון בייביסיטר",
    preferenceInfancy: "גיל הרך",
    preferenceSpecialEducation: "חינוך מיוחד",
    preferenceAgeFive: "גיל 5 ומעלה",
    preferenceRewards: "תגמולים",
    preferenceWithoutFood: "בלי אוכל",
    preferenceNoHomework: "בלי שיעורי בית",
  },
} as const;
